### PR TITLE
Add PTS files

### PR DESCRIPTION
**Pull request by C-D-Lewis**
Ping @sarfata for review

### CODE REVIEW

**Comment by sarfata** [comment]
I do not think we should put dates in filenames in github. Github provides history. Can you rename the files?

**Comment by sarfata** [comment]
Both files should also have the same content so they should have the same name and only the extension will change.

**Comment by C-D-Lewis** [comment]
@sarfata Files have been renamed.

**Comment by sarfata** [comment]
:+1:

**Pull request merged**
