### PR TITLE
Fix STL for 3D printing

### PR DESCRIPTION
**Pull request by faberdasher**
STL was fixed for easier 3d printing:
- Orientated for better quality (less overhangs).
- Mesh was made manifold.
- Reduced degenerate mesh faces.

### CODE REVIEW

**Comment by nhitze** [comment]
thumbs up!

**Comment by trbielec** [comment]
Nicely done!

**Comment by sarfata** [comment]
Thanks guys. Super helpful. We will test to make sure everything is still ok and merge. 

Can you tell us how you fixed it so that in the future I can make sure our files are clean out of the box?

**Comment by sarfata** [comment]
We fixed all three files in #7. We chose to push our files rather than merge this PR because we wanted to make sure we had a repeatable process to produce them and future files. 

Thanks a lot for your help here. If you have any extra feedback please keep shooting.

**Pull request closed without merging**
